name: Wii-Build
on:
  push:
    branches:
    - fast
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          .
